Controllers/admin_ContactController.cs
using CorrectTemp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BWA_CB006302.Controllers
{
    public class admin_ContactController : Controller
    {
        // GET: admin_Contact
        public ActionResult admin_Contact()
        {
            return View();
        }
        public ActionResult admin_Reply()
        {
            ViewBag.Title = "admin_Reply";
            return View();
        }

        [HttpPost]
        public ActionResult admin_Reply_msg(Message msg)
        {
            if (CorrectTemp.DataAccess.DA.admin_Message(msg.msgID, msg.username, msg.subject, msg.messageDetail, msg.reciever))
            {
                return RedirectToAction("../Home/admin_Index");
            }
            else
            {
                ModelState.AddModelError("", "Message sending failed. Try again!");
            }
            return View();
        }
        public ActionResult admin_Inbox()
        {
            var user = Session["userSession"];
            using (var context = new BWAEntities())
            {
                var message = context.Messages.SqlQuery("SELECT * FROM dbo.Message where reciever='"+user+"'").ToList();

                return View(message);
            }
        }
        public ActionResult admin_Remove_mail(int id)
        {
            if (CorrectTemp.DataAccess.DA.remove_mail(id) == true)
            {

                return RedirectToAction("../admin_Contact/admin_Inbox");
            }
            else
            {
                ModelState.AddModelError("", "Something went wwrong. Try again!");
            }
            return View();

        }
    }
}

Views/admin_Contact/admin_Inbox.cshtml
@model IEnumerable<CorrectTemp.Models.Message>

@{
    ViewBag.Title = "admin_Inbox";
    Layout = "~/Views/Shared/admin_layout.cshtml";
}

<div class="left-content">
    <!--inner block start here-->
    <div class="col-md-8 mailbox-content  tab-content tab-content-in">
        <div class="tab-pane active text-style" id="tab1">
            <div class="mailbox-border">
                <table class="table tab-border">
                    <tbody>
                        @foreach (CorrectTemp.Models.Message msg in @Model)
                        {
                            using (Html.BeginForm("admin_Remove_mail", "admin_Contact", new { id = msg.msgID }))
                            {
                                <tr class="unread checked" align="center">
                                    <td class="hidden-xs"><input type="submit" value="Delete" /></td>
                                    <td class="hidden-xs">@msg.username</td>
                                    <td>@msg.subject</td>
                                    <td>@msg.messageDetail</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
            <div class="compose-block" align="center">
                <div class="fa fa-envelope-o" style="align-content:center; border: none">@Html.ActionLink(" Compose", "admin_Reply", "admin_Contact")</div>
            </div>
        </div>
    </div>
</div>

Views/admin_Contact/admin_Reply.cshtml
@model CorrectTemp.Models.Message

@{
    ViewBag.Title = "admin_Reply";
    Layout = "~/Views/Shared/admin_layout.cshtml";
}

<!-- start contact section -->
<section id="aa-contact">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="aa-contact-area">
                    <div class="aa-contact-address">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="aa-contact-address-left">
                                    @using (Html.BeginForm("admin_Reply_msg", "admin_Contact", FormMethod.Post, new { @class = "comments-form contact-form" }))
                                    {
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    @Html.TextBoxFor(m => m.username, new { placeholder = "Admin username", @class = "form-control" })
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    @Html.TextBoxFor(m => m.reciever, new { placeholder = "Send to", @class = "form-control" })
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">          
                                                <div class="form-group">
                                                    @Html.TextBoxFor(m => m.subject, new { placeholder = "Subject", @class = "form-control" })
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.TextAreaFor(m => m.messageDetail, new { placeholder = "Message", @class = "form-control" })
                                        </div>
                                        <button class="aa-secondary-btn">Send</button>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>