Controllers/AddProductsController.cs
using BWA_CB006302.Models;
using CorrectTemp.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BWA_CB006302.Controllers
{
    public class AddProductsController : Controller
    {
        // GET: AddProducts
        public ActionResult AddProducts()
        {
            return View(); 
        }

        [HttpPost]
        public ActionResult AddProducts(upload_image upload)
        {
            Product pro = new Product();
            if(upload.file.ContentLength > 0){
                var fileName = Path.GetFileName(upload.file.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/img"), fileName);
                upload.file.SaveAs(path);
            }
            return View("addProductDetails");
        }

        public ActionResult addProductDetails()
        {
            Product pro = new Product();
            pro.ItemID = Request["itemID"];
            pro.ItemName= Request["ItemName"];
            pro.ItemDescription = Request["ItemDescription"];
            pro.Stock=  Convert.ToInt32(Request["Stock"]);
            pro.Discount = Convert.ToInt32(Request["Discount"]);
            pro.Price = Convert.ToInt32(Request["Price"]);
            pro.ItemAvailability=Request["radiobtn"];
            pro.ItemCategory = Request["radiobtnCategory"];

                if (CorrectTemp.DataAccess.DA.addItem(pro.ItemID, pro.ItemName, pro.ItemDescription, (int)pro.Stock, (int)pro.Discount, (int)pro.Price, pro.ItemAvailability, pro.ItemCategory))
                {
                    return RedirectToAction("../AddProducts/AddProducts");
                }
                else
                {
                    ModelState.AddModelError("", "There was a problem, try again!");
                }
            
            
            return View();
        }
        public ActionResult viewProducts() {
            using (var context = new BWAEntities())
            {
                var prod = context.Products.SqlQuery("SELECT * FROM dbo.Product").ToList();

                return View(prod);
            }
        }
        public ActionResult admin_Remove_Product(string id)
        {
            if (CorrectTemp.DataAccess.DA.remove_product(id) == true)
            {

                return RedirectToAction("../AddProducts/viewProducts");
            }
            else
            {
                ModelState.AddModelError("", "Something went wwrong. Try again!");
            }
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BWA_CB006302.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ViewBag.Title = "Home";
            return View();
        }
        public ActionResult admin_Index()
        {
            ViewBag.Title = "admin_Index";
            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Title = "Contact";
            return View("Contact");
        }
        public ActionResult myAccount()
        {
            ViewBag.Title = "My Account";
            return View("myAccount");
        }
        public ActionResult Cart()
        {
            ViewBag.Title = "Cart";
            return View("Cart");
        }
        public ActionResult Checkout()
        {
            ViewBag.Title = "Checkout";
            return View("Checkout");
        }
    }
}

Controllers/ProductController.cs
using CorrectTemp.Controllers;
using CorrectTemp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BWA_CB006302.Controllers
{
    public class ProductController : Controller
    {
        BWAEntities DbProd = new BWAEntities();
        BWAEntities DbCart = new BWAEntities();

        public ActionResult Product()
        {
            using (var context = new BWAEntities())
            {
                var men_product = context.Products.SqlQuery("select * from Product where ItemCategory='Men'").ToList();

                return View(men_product);
            }
        }
        public ActionResult women()
        {
            using (var context = new BWAEntities())
            {
                var women_product = context.Products.SqlQuery("select * from Product where ItemCategory='Women'").ToList();

                return View(women_product);
            }
        }
        public ActionResult add_to_cart(string id)
        {
            BWAEntities context = new BWAEntities();
            if (Session["cart"] == null)
            {
                List<Product> cart = new List<Product>();
                cart.Add(context.Products.Single(x=> x.ItemID == id));
                Session["cart"] = cart;
            }
            else
            {
                List<Product> cart = (List<Product>)Session["cart"];
                int a = addExistingItem(id);
                if (a == -1)
                    cart.Add(context.Products.Single(x => x.ItemID == id));
                else
                    cart[a].Quantity++;
                    Session["cart"] = cart;
            }
            return View("Cart");
        }
        public ActionResult delete(string id) {

            int a = addExistingItem(id);
            List<Product> cart = (List<Product>)Session["cart"];
            cart.RemoveAt(a);
            Session["cart"] = cart;
            return View("Cart");
        }
        public ActionResult ProductDetails()
        {
            ViewBag.Title = "ProductDetails";
            return View();
        }
        private int addExistingItem(string id)
        {
            List<Product> cart = (List<Product>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].ItemID == id)
                    return i;
            return -1;
        }
        public ActionResult checkout_cart()
        {
            List<Product> cart_ = (List<Product>)Session["cart"];

            if (CorrectTemp.DataAccess.DA.userCart(cart_, (string)Session["userSession"]))
                {
                    ViewBag.Success = "Your purchse was successfully placed.";
                   Session.Remove("cart");
                    return View("../Home/Index");
                }
                else
                {
                    ModelState.AddModelError("", "There was a problem, try again!");
                }
            
            return View("Cart");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<!-- Start Promo section -->
<section id="aa-promo">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="aa-promo-area">
                    <div class="row">
                        <!-- promo left -->
                        <div class="col-md-5 no-padding">
                            <div class="aa-promo-left">
                                <div class="aa-promo-banner">
                                    <img src="@Url.Content("~/Content/")img/promo-men.jpg" alt="img">
                                    <div class="aa-prom-content">
                                        <span>@CorrectTemp.Resources.lang.SeventyFive_off</span>
                                        <h4>@Html.ActionLink(CorrectTemp.Resources.lang.For_Men, "Product", "Product")</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- promo right -->
                        <div class="col-md-7 no-padding">
                            <div class="aa-promo-right">
                                <div class="aa-single-promo-right">
                                    <div class="aa-promo-banner">
                                        <img src="@Url.Content("~/Content/")img/promo-women.jpg" alt="img">
                                        <div class="aa-prom-content">
                                            <span>@CorrectTemp.Resources.lang.Exclusive_Item</span>
                                            <h4>@Html.ActionLink(CorrectTemp.Resources.lang.For_Women, "women", "Product")</h4>
                                        </div>
                                    </div>
                                </div>
                                <div class="aa-single-promo-right">
                                    <div class="aa-promo-banner">
                                        <img src="@Url.Content("~/Content/")img/promo-shoes.jpg" alt="img">
                                        <div class="aa-prom-content">
                                            <span>Sale Off</span>
                                            <h4><a href="#">@Html.ActionLink(CorrectTemp.Resources.lang.On_Shoes, "Product", "Product")</a></h4>
                                        </div>
                                    </div>
                                </div>
                                <div class="aa-single-promo-right">
                                    <div class="aa-promo-banner">
                                        <img src="@Url.Content("~/Content/")img/kids-promo.jpg" alt="img">
                                        <div class="aa-prom-content">
                                            <span>@CorrectTemp.Resources.lang.New_Arrivals</span>
                                            <h4><a href="#">@Html.ActionLink(CorrectTemp.Resources.lang.For_Kids, "Product", "Product")</a></h4>
                                        </div>
                                    </div>
                                </div>
                                <div class="aa-single-promo-right"> 
                                    <div class="aa-promo-banner">
                                        <img src="@Url.Content("~/Content/")img/promo-bags.jpg" alt="img">
                                        <div class="aa-prom-content">
                                            <span>@CorrectTemp.Resources.lang.twentyfive</span>
                                            <h4>@Html.ActionLink(CorrectTemp.Resources.lang.For_Bags, "Product", "Product")</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- / Promo section -->

<!-- Support section -->
<section id="aa-support">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="aa-support-area">
                    <!-- single support -->
                    <div class="col-md-4 col-sm-4 col-xs-12">
                        <div class="aa-support-single">
                            <span class="fa fa-truck"></span>
                            <h4>@CorrectTemp.Resources.lang.Free_Ship</h4>
                        </div>
                    </div>
                    <!-- single support -->
                    <div class="col-md-4 col-sm-4 col-xs-12">
                        <div class="aa-support-single">
                            <span class="fa fa-clock-o"></span>
                            <h4>@CorrectTemp.Resources.lang.MoneyBack</h4>
                        </div>
                    </div>
                    <!-- single support -->
                    <div class="col-md-4 col-sm-4 col-xs-12">
                        <div class="aa-support-single">
                            <span class="fa fa-phone"></span>
                            <h4>@CorrectTemp.Resources.lang.Support</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- / Support section -->

<!-- Testimonial -->
<section id="aa-testimonial">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="aa-testimonial-area">
                    <ul class="aa-testimonial-slider">
                        <!-- single slide -->
                        <li>
                            <div class="aa-testimonial-single">
                                <p>@CorrectTemp.Resources.lang.About_us</p>
                                <div class="aa-testimonial-info">

                                    <span>@CorrectTemp.Resources.lang.About_firstline</span><br>

                                    <span>@CorrectTemp.Resources.lang.About_secondline</span>

                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- / Testimonial -->

   
<!-- Client Brand -->
<section id="aa-client-brand">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="aa-client-brand-area">
                    <ul class="aa-client-brand-slider">
                        <li><a href="#"><img src="@Url.Content("~/Content/")img/client-brand1.png" alt="java img"></a></li>
                        <li><a href="#"><img src="@Url.Content("~/Content/")img/client-brand2.png" alt="jquery img"></a></li>
                        <li><a href="#"><img src="@Url.Content("~/Content/")img/client-brand3.png" alt="html5 img"></a></li>
                        <li><a href="#"><img src="@Url.Content("~/Content/")img/client-brand4.png" alt="css3 img"></a></li>
                        <li><a href="#"><img src="@Url.Content("~/Content/")img/client-brand5.png" alt="wordPress img"></a></li>
                       
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- / Client Brand -->



<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="@Url.Content("~/Content/")js/bootstrap.js"></script>
<!-- SmartMenus jQuery plugin -->
<script type="text/javascript" src="@Url.Content("~/Content/")js/jquery.smartmenus.js"></script>
<!-- SmartMenus jQuery Bootstrap Addon -->
<script type="text/javascript" src="@Url.Content("~/Content/")js/jquery.smartmenus.bootstrap.js"></script>
<!-- Product view slider -->
<script type="text/javascript" src="@Url.Content("~/Content/")js/jquery.simpleGallery.js"></script>
<script type="text/javascript" src="@Url.Content("~/Content/")js/jquery.simpleLens.js"></script>
<!-- slick slider -->
<script type="text/javascript" src="@Url.Content("~/Content/")js/slick.js"></script>
<!-- Price picker slider -->
<script type="text/javascript" src="@Url.Content("~/Content/")js/nouislider.js"></script>

<!-- Custom js -->
<script src="@Url.Content("~/Content/")js/custom.js"></script> 

Views/Home/admin_Index.cshtml
@{
    ViewBag.Title = "admin_Index";
    Layout = "~/Views/Shared/admin_layout.cshtml";
}

<section id="menu">
    <div class="container">
        <div class="menu-area">
            <!-- Navbar -->
            <div class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

            </div>
        </div>
    </div>
</section>
<!-- / menu -->
<!-- Start slider -->
<section id="aa-slider">

    <div class="aa-slider-area">
        <div id="sequence" class="seq">
            <ul class="seq-canvas">
                <!-- single slide item -->
                <li>
                    <div class="seq-model">
                        <img data-seq src="@Url.Content("~/Content/")img/slider/adminSlider1.jpg"/>
                    </div>
                    <div class="seq-title">
                        <form action="">
                            <div class="aa-shop-now-btn aa-secondary-btn">@Html.ActionLink("Compose message", "admin_Reply", "admin_Contact")</div><br />
                            <div class="aa-shop-now-btn aa-secondary-btn">@Html.ActionLink("Check inbox", "admin_Inbox", "admin_Contact")</div><br />
                            <div class="aa-shop-now-btn aa-secondary-btn">@Html.ActionLink("Add products", "AddProducts", "AddProducts")</div><br />
                            <div class="aa-shop-now-btn aa-secondary-btn">@Html.ActionLink("Sales", "totalSales", "Sales")</div><br />
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</section>
<!-- / slider -->